# Primary domain application will be accessed as 
:domain: sims.widpi.managedmachine.com  #wisims.org 

:default_url: https://staging.sims.widpi.managedmachine.com

# Domain aliases for applaction. One common use of this is for asset hosts.
:domain_aliases:
  - *.staging.sims.widpi.managedmachine.com
#  - assets2.sims.managedmachine.com


